config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount ActionCable.server => "/cable"

  root 'pages#home'
  #root 'notifications#index'

	devise_for :users
	
  #root 'places#index'

  scope :path => '/api/v1/', :module => "api_v1", :defaults => { :format => :json }, :as => 'v1' do
 
    post "/login" => "auth#login"
    post "/logout" => "auth#logout"
    post "/new" => "auth#new"
    #post "/places" => "places#show"
 
    get "search" => "pages#get_nearby"
    
    resources :places
    resources :reservations
    resources :pages
    
  end

  resources :notifications

  resources :users, only: [:show]
  resources :places

  resources :places do
    resources :reservations, only: [:create, :edit, :index, :show, :update]
  end

  resources :places do
    resources :reviews, only: [:create, :destroy]
  end

  resources :reservations

  resources :pages

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload' => 'reservations#preload'


  resources :photos

  get '/your_trips' => 'reservations#your_trips'

  get '/search' => 'pages#search'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root :to => "welcome#index"
  #root :to => "posts#index"
  
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, foreign_key: :sender_id, class_name: 'user'
	belongs_to :recipient, foreign_key: :recipient_id, class_name: 'user'

	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :recipient_id

	scope :involving, -> (user) do 
		where("conversations.sender_id = ? OR conversations.recipient_id =? ", user.id, user.id)
	end

	scope :between, -> (sender_id, recipient_id) do
		where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", 
					sender_id, recipient_id, recipient_id, sender_id)
	end

 	
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!

	def index
		@users = User.all
		@conversations = Conversation.involving(current_user)
	end

	def create
		if Conversation.between(params[:sender_id], params[:recipient_id]).present?
			@conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
		else
			@conversation = Conversation.create(conversation_params)
		end

		redirect_to conversation_messages_path(@conversation)
	end

	private

	def conversation_params
		params.permit(:sender_id, :recipient_id)
	end
end

app/views/conversations/index.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panal-heading">Your conversations</div>
				<div class="panel-body">

						<div class="container">
							<% @conversations.each do |conversation|%>
								
								<% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
	    						<% if conversation.sender_id == current_user.id %>
	      						<% recipient = User.find(conversation.recipient_id) %>
	    						<% else %>
	      						<% recipient = User.find(conversation.sender_id) %>
	    						<% end %>
   							<% end %>
								
								<%= link_to conversation_messages_path(conversation) do %>
								
									<div class="row conversation">
										<div class="col-md-2">
											
										</div>

									<div class="col-md-2">
										<%= recipient.nickname %>
										<%= conversation.messages.last.message_time %>
									</div>

									<div class="col-md-8">
										<%= conversation.messages.last.content %>
									</div>

									</div>
								<% end %>
							<% end %>
						</div>
				</div>
			</div>

<h3>All Users</h3>
	<% @users.each do |user| %>
		<% if user != current_user %>
			<%= user.nickname %>
			<%= link_to "Send Message", conversations_path(sender_id: current_user, recipient_id: user.id ), :method => :post%>
		<% end %>
	<% end %>
	</div>
</div>