config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount ActionCable.server => "/cable"

  root 'pages#home'
  #root 'notifications#index'

	devise_for :users
	
  #root 'places#index'

  scope :path => '/api/v1/', :module => "api_v1", :defaults => { :format => :json }, :as => 'v1' do
 
    post "/login" => "auth#login"
    post "/logout" => "auth#logout"
    post "/new" => "auth#new"
    #post "/places" => "places#show"
 
    get "search" => "pages#get_nearby"
    
    resources :places
    resources :reservations
    resources :pages
    
  end

  resources :notifications

  resources :users, only: [:show]
  resources :places

  resources :places do
    resources :reservations, only: [:create, :edit, :index, :show, :update]
  end

  resources :places do
    resources :reviews, only: [:create, :destroy]
  end

  resources :reservations

  resources :pages

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload' => 'reservations#preload'


  resources :photos

  get '/your_trips' => 'reservations#your_trips'

  get '/search' => 'pages#search'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root :to => "welcome#index"
  #root :to => "posts#index"
  
end

app/models/notification.rb
class Notification < ApplicationRecord
	after_create_commit { NotificationBroadcastJob.perform_later(Notification.count)}
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  def index
  	@notifications = Notification.all.reverse
  end

  def destroy
  	@notification = Notification.find(params[:id])
  	@notification.destroy

    redirect_to :back
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_notification.html.erb
<li>
  <%= notification.event %>
  	<span> <%= notification.created_at.strftime("%d %b. %Y") %></span>
  <%= link_to "x", notification_path(notification), :method => :delete %>
</li>

app/views/notifications/_notification_center.html.erb
<ul class="notificator">
	<a href="#" id="open_notification">
    <%= render 'events/counter', counter: notifications.count %>
  </a>
  <div id="notificationContainer">
    <div id="notificationTitle">所有通知</div>
    <div id="notificationsBody" class="notifications">
      <ul id="notificationList">
        <%= render notifications %>
      </ul>
    </div>

    <div id="notificationFooter"></div>

  </div>

</ul>

<script>

	//$(document).ready('turbolinks:load', function()	
	$(document).on('turbolinks:load', (function()
		{
			$("#open_notification").click(function()
	    // open notification center on click
	    //$("#open_notification").click(function()
	    {
	        $("#notificationContainer").fadeToggle(300);
	        $("#notification_count").fadeOut("fast");
	        return false;
	    });
	 
	    // hide notification center on click
	    $(document).click(function()
	    {
	        $("#notificationContainer").hide();
	    });
	 
	 
	    $("#notificationContainer").click(function()
	    {
	        return false;
	    });
		}
	);
</script>

app/views/notifications/index.html.erb
<h1>Notifications#index</h1>
<p>Find me in app/views/notifications/index.html.erb</p>

<%= render "notification_center", notifications: @notifications %>
<%#= render "notification", notifications: @notifications %>