config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount ActionCable.server => "/cable"

  root 'pages#home'
  #root 'notifications#index'

	devise_for :users
	
  #root 'places#index'

  scope :path => '/api/v1/', :module => "api_v1", :defaults => { :format => :json }, :as => 'v1' do
 
    post "/login" => "auth#login"
    post "/logout" => "auth#logout"
    post "/new" => "auth#new"
    #post "/places" => "places#show"
 
    get "search" => "pages#get_nearby"
    
    resources :places
    resources :reservations
    resources :pages
    
  end

  resources :notifications

  resources :users, only: [:show]
  resources :places

  resources :places do
    resources :reservations, only: [:create, :edit, :index, :show, :update]
  end

  resources :places do
    resources :reviews, only: [:create, :destroy]
  end

  resources :reservations

  resources :pages

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload' => 'reservations#preload'


  resources :photos

  get '/your_trips' => 'reservations#your_trips'

  get '/search' => 'pages#search'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root :to => "welcome#index"
  #root :to => "posts#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	belongs_to :sender, foreign_key: :sender_id, class_name: 'user'
	belongs_to :recipient, foreign_key: :recipient_id, class_name: 'user'

	has_many :messages, dependent: :destroy

	validates_uniqueness_of :sender_id, scope: :recipient_id

	scope :involving, -> (user) do 
		where("conversations.sender_id = ? OR conversations.recipient_id =? ", user.id, user.id)
	end

	scope :between, -> (sender_id, recipient_id) do
		where("(conversations.sender_id = ? AND conversations.recipient_id = ?) OR (conversations.sender_id = ? AND conversations.recipient_id = ?)", 
					sender_id, recipient_id, recipient_id, sender_id)
	end

 	
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  validates_presence_of :content, :conversation_id, :user_id

  def message_time
  	created_at.strftime("%v")
  end

end

app/models/notification.rb
class Notification < ApplicationRecord
	after_create_commit { NotificationBroadcastJob.perform_later(Notification.count)}
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :place

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/place.rb
class Place < ApplicationRecord

	belongs_to :user
	has_many :photos, :dependent => :destroy

	geocoded_by :address
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

	has_many :reservations

	has_many :reviews

	def average_rating
		reviews.count == 0 ? 0 : reviews.average(:star).round(2)
	end

	def check_big_bag(total_reservations)
	 	total = 0
	 	
    total_reservations.each do |b| 
      total = total + b.big_bags_for_thistime
    end
    return total
	 end

	 def check_small_bag(total_reservations)
	 	total = 0
	 	
    total_reservations.each do |b| 
      total = total + b.small_bags_for_thistime
    end
    return total
	 end
	
end

app/models/reservation.rb
class Reservation < ApplicationRecord

	after_create_commit { notify }

	belongs_to :user

	belongs_to :place

	#belongs_to :reservation_status


	
	def time_diff(start_time, end_time)
	  seconds_diff = (start_time - end_time).to_i.abs

	  hours = seconds_diff / 3600
	  seconds_diff -= hours * 3600

	  minutes = seconds_diff / 60
	  seconds_diff -= minutes * 60

	  seconds = seconds_diff

	  "#{hours.to_s.rjust(2, '0')}:#{minutes.to_s.rjust(2, '0')}:#{seconds.to_s.rjust(2, '0')}"
	 end

	 def check_big_bag (total_reservations)
	 	total = 0
	 	
    total_reservations.each do |b|
      total = total + b.big_bags_for_thistime
    end
	 end

	private
 
  	def notify
    	Notification.create(event: "你有一筆新訂單")
  	end

end

app/models/reservation_status.rb
class ReservationStatus < ApplicationRecord
	has_many :reservations
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :place
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  before_create :generate_authentication_token
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include Gravtastic
  gravtastic

  

  has_many :places, :dependent => :destroy

  has_many :reservations

  has_many :reviews

  def generate_authentication_token
     self.authentication_token = Devise.friendly_token
  end

end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
	
	#before_action :authenticate_user_from_token!
	
  def authenticate_user_from_token!

    if params[:auth_token].present?
      user = User.find_by_authentication_token(
                  params[:auth_token] )

      sign_in(user, store: false) if user
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def index
  	@q = Place.ransack(params[:q])
  	@R_places = @q.result
  end

  def home
  	@places = Place.all.order("id DESC")
  end

  def show
  	@place = Place.find(params[:id])
  end

  def search

		if params[:search].present? && params[:search].strip != ""
			p = params[:search]
		end

		if p && p != ""
			@places_address = Place.near(p, 1500, order: 'distance').limit(5)
		else
			byebug
			@places_address = Place.all
		end


		@search = @places_address.ransack(params[:q])
		@places = @search.result
		@arrPlaces = @places.to_a

	end


  
end

app/controllers/photo_controller.rb
class PhotosController <ApplicationController

	def destroy
		@photo = Photo.find(params[:id])
		place = @photo.place

		@photo.destroy
		@photos = Photo.where(:place_id => place_id)

		respond_to :js
	end
end

app/controllers/photos_controller.rb
class PhotosController <ApplicationController

	def destroy
		@photo = Photo.find(params[:id])
		place = @photo.place

		@photo.destroy
		@photos = Photo.where(:place_id => place_id)

		respond_to :js
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find_by_id(params[:id])
		@places = @user.places
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_url(user)
		gravatar_id = Digest::MD5::hexdigest(user.email).downcase 
		if user.image
			#user.image
		else
			#{}"https://www.gravatar.com/avatar/#{gravatar_id}.jpg?d=identical&s=150"
		end
	end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/events/_counter.html.erb
<li >
  <%= image_tag("icons/notification_bell.svg") %>
  <span  id="notification-counter"><%= counter %></span>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>寄物便 BagKeeper</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.11.3/themes/smoothness/jquery-ui.css">    
    
  </head>

  <body style=" padding-top: 0px ">

  <%= render 'shared/navbar' unless @disable_nav %>
  <%= render 'shared/message' %>
  
  
    <%= yield %>
 

  </body>
</html>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |f| %>
			<% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
			toastr['<%= type %>']('<%= f[1] %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">

          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>

          </button>
          <a class="navbar-brand" href="">寄物便 Bag Keeper</a>
          
        </div>
        <div id="navbar" class="navbar-collapse collapse">

          <ul class="nav navbar-nav navbar-right">
            
            <% if (!user_signed_in?)%>
              <li><%= link_to('註冊', new_registration_path(:user)) %></li> 
              <li><%= link_to('登入', new_session_path(:user)) %></li>
            <% else %>
           
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">

      
              <%= current_user.nickname %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Your Trips", your_trips_path %></li>
                <li><%= link_to "Your Places", places_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to('登出', destroy_user_session_path, :method => :delete) %></li>
              </ul>
            </li>

            <% end %>

            <li>
              <%= link_to new_place_path do %>
                <i class="fa fa-envelope-o"></i> 發送訊息
              <% end %>
            </li>
            
            <li>
              <%= link_to new_place_path do %>
                <i class="fa fa-home fa-lg"></i> 建立新地點
              <% end %>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>