config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount ActionCable.server => "/cable"

  root 'pages#home'
  #root 'notifications#index'

	devise_for :users
	
  #root 'places#index'

  scope :path => '/api/v1/', :module => "api_v1", :defaults => { :format => :json }, :as => 'v1' do
 
    post "/login" => "auth#login"
    post "/logout" => "auth#logout"
    post "/new" => "auth#new"
    #post "/places" => "places#show"
 
    get "search" => "pages#get_nearby"
    
    resources :places
    resources :reservations
    resources :pages
    
  end

  resources :notifications

  resources :users, only: [:show]
  resources :places

  resources :places do
    resources :reservations, only: [:create, :edit, :index, :show, :update]
  end

  resources :places do
    resources :reviews, only: [:create, :destroy]
  end

  resources :reservations

  resources :pages

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  get '/preload' => 'reservations#preload'


  resources :photos

  get '/your_trips' => 'reservations#your_trips'

  get '/search' => 'pages#search'

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root :to => "welcome#index"
  #root :to => "posts#index"
  
end

app/models/place.rb
class Place < ApplicationRecord

	belongs_to :user
	has_many :photos, :dependent => :destroy

	geocoded_by :address
	after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

	reverse_geocoded_by :latitude, :longitude
	after_validation :reverse_geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

	has_many :reservations

	has_many :reviews

	def average_rating
		reviews.count == 0 ? 0 : reviews.average(:star).round(2)
	end

	def check_big_bag(total_reservations)
	 	total = 0
	 	
    total_reservations.each do |b| 
      total = total + b.big_bags_for_thistime
    end
    return total
	 end

	 def check_small_bag(total_reservations)
	 	total = 0
	 	
    total_reservations.each do |b| 
      total = total + b.small_bags_for_thistime
    end
    return total
	 end
	
end

app/controllers/api_v1/places_controller.rb
class ApiV1::PlacesController < ApiController
  
  before_action :authenticate_user!
  
	def index
    #@places = Place.all.order("id DESC")
    @places = current_user.places.order("id DESC")

    # render :json => @places.to_json

    # result = {}

    # @places.each do |p|
    #   h = { :shop_name => p.shop_name, :address => p.address }
    #   result[p.id.to_s.to_sym] = h
    # end

    # render :json => result.to_json
  end

  def show
    @place = Place.find(params[:id])

    render :json => @place.to_json
  end
 
  def create
    @place = Place.new( :shop_name => params[:shop_name] )
 
    if @place.save
    	render :json => { :message => "OK", :id => @place.id }
    else
    	render :json => { :errors => @place.errors.full_messages }, :status => 400
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController

  before_action :find_place, :only => [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index]

  def index
    @places = current_user.places.order('created_at DESC')

    #@wait_to_place_reservations = 
      #<!--Place.find('10').reservations.first.status-->
    #@wait_to_take_reservations
    #@completed_reservations

  end

  def show
    @photos = @place.photos

    @booked = Reservation.where("place_id = ? AND user_id = ?", @place_id, current_user.id).present? if current_user
    
    @reviews = @place.reviews
    @hasReview = @reviews.find_by(:user_id => current_user.id) if current_user
    #@shop_reservations = @place.reservations

    total_reservations = @place.reservations.where({status: ["待寄放", "待取"]})
    
    @R_place = @place.check_big_bag(total_reservations)
    @r_place = @place.check_small_bag(total_reservations)

    @place.currnet_big_capacity = @R_place
    @place.currnet_small_capacity = @R_place

    @place.save

    
  end

  def new
    @place = current_user.places.new
  end

  def edit
    if current_user.id == @place.user_id
      @photos = @place.photos
    else
      redirect_to root_path, notice: "No permission"
    end
  end

  def create
    @place = current_user.places.build(place_params)

    if @place.save
      if params[:images]
        params[:images].each do |image|
          @place.photos.create(image: image)
        end
      end

      @photos = @place.photos
      redirect_to edit_place_path(@place), notice: "Saved!"
    else
      render :new
    end

  end

  def update
    if @place.update(place_params)

      if params[:images]
        params[:images].each do |image|
          @place.photos.create(image: image)
        end
      end

      redirect_to edit_place_path(@place), notice: "Updated!"
    else
      render :edit
    end
  end

  def destroy
    if @place.destroy
      redirect_to places_path, notice: "deleted!"
    end
  end


  private 

  def place_params
    params.require(:place).permit(:shop_name, :address, :summary, :big_bag, :small_bag)
  end

  def find_place
    @place = Place.find(params[:id])
  end

end

app/helpers/api_v1/places_helper.rb
module ApiV1::PlacesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		Create your place to put bags
	</div>

	<div class="panel-body">
		<div class="container ">
			<%= form_for @place, :html => {:multipart => true} do |p| %>
				<div class="row">
					<div class="col-md-4">
						<div class="form-group">
							<label> Shop Name </label>
								<%= p.text_field :shop_name, placeholder: "What is your shopname?", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4">
						<div class="form-group">
							<label> Allow how manny BIG bags </label>
								<%= p.text_field :big_bag, placeholder: "How many you wil provide?", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4">
						<div class="form-group">
							<label> Allow how manny small bags </label>
								<%= p.text_field :small_bag, placeholder: "How many you wil provide?", class: "form-control" %>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label> Shop Address </label>
								<%= p.text_field :address, placeholder: "What is your adress?", class: "form-control" %>
						</div>
					</div>

					<div class="col-md-4">
						<div class="form-group">
							<label> Shop Phone </label>
								<%= p.text_field :phone, placeholder: "What is your phone?", class: "form-control" %>
						</div>
					</div>
				</div>
				
				<div class="row">
					<div class="col-md-10">
						<div class="form-group">
							<label> Shop Summary </label>
								<%= p.text_area :summary, rows: 5, placeholder: "Tell about your place", class: "form-control" %>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-4">
						<div class="form-group">
							<span class ="btn btn-default btn-file">
								<i class ="fa fa-cloud-upload fa-lg"></i> Upload Photos
								<%= file_field_tag "images[]", :type => :file, multiple: true %>
							</span>
						</div>
					</div>
				</div>

				<div id="photo"><%= render 'photos/list'%></div>

				<div class="actions">
					<%= p.submit "Save", class: "btn btn-primary" %>
				</div>
				
			<% end%>			
		</div>
	</div>
</div>

app/views/places/dstroy.html.erb
<h1>Places#dstroy</h1>
<p>Find me in app/views/places/dstroy.html.erb</p>

app/views/places/edit.html.erb
<%= render 'form' %>

app/views/places/index.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="sidebar-list">

			<form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>

		</ul>
	</div>


	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Your Places
				<!--Place.find('10').reservations.first.reservation_status.bag_status-->
			</div>
			<div class="panel-body">
				<% @places.each do |place| %>
					<div class="row">
						<div class="col-md-2 bgc" style="height:100px; background-color: white;">				
								<%= image_tag place.photos[0].image.url(:thumb) if place.photos.length >0 %>
						</div>
						<div class="col-md-6">
							<h4><%= place.shop_name %></h4>
							<p><% place.reservations.each do |r|%>
								| <%= r.order_id if r.order_id != '11111111' %>
								<%= link_to r.status, place_reservation_path(place, r) if r.status != '完成'%>
								<%end %>
							</p>
						</div>
						<div class="col-md-4 right">
							
							<%= link_to "顯示所有訂單", place_reservations_path(place), class: "btn btn-primary"%>
							<%= link_to "更新", edit_place_path(place), class: "btn btn-primary"%>
							<%= link_to "刪除", place_path(place), :method => :delete, class: "btn btn-primary"%>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/places/new.html.erb
<%= render "form" %>

app/views/places/show.html.erb
<div class="panel panel-defaut">
	<div class="panel-body">
		<!--IMG-->
		<div class="row">
			<div class="col-md-12">
				<% if @photos[0] %>
				<%= image_tag @photos[0].image.url(), class: "img-responsive"%>
				<% end %>
			</div>
		</div>

		<br>

		<!--Main-->
		<div class="row">
			<div class="col-md-7">
				<div class="row">
					<div class="col-md-3 text-center">
						屋主
						<%= @place.user.nickname %>
						<br>
						<%= image_tag current_user.gravatar_url %>
					</div>
					<div class="col-md-9">
						<h4><%= @place.shop_name %></h4>
						<h5><%= @place.address %></h5> 

						<!--
						<p>Coordinates: <%= @place.latitude %> <%= @place.longitude %></p>
						-->
						<div class="row text-center row-space-1">
							<div class="col-md-3">
								<i class="fa fa-shopping-bag fa-2x"></i>
							</div>
							
							<div class="col-md-3">
								<i class="fa fa-suitcase fa-2x"></i>
							</div>
						</div>

						<!-- Reservation.where( status: "待寄放") -->
						

						<div class="row text-center">
							<div class="col-md-3">
								Big: <%= @place.big_bag %>
								<br>
								Usage :<%= @R_place %>
							</div>
							
							<div class="col-md-3">
								Small: <%= @place.small_bag %>
								<br>
								Usage :<%= @r_place %>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="col-md-5">
				<!--Reservation-->
				<% if @place.small_bag == @r_place && @place.big_bag == @r_place%>
					This place is FULL
				<% else %>
					<%= render 'reservations/form'%>
				<% end%>

			</div>
		</div>

		<div class="row">
			<div class="col-md-12">
				<h2>About this Place</h2>
				<%= @place.summary %>
			</div>
		</div>

		<!-- Reviews, if @booked && !@hasReview, <%= @place.average_rating %>-->
		<div class="row">
			<div class="col-md-12">
				<h3>Reviews <%= @place.average_rating%> (<%= @reviews.count %>)</h3>
				<div class="container">
					<div>
						<%= render 'reviews/form'%>
					</div>
					<div>
						<%= render 'reviews/list'%>
					</div>
				</div>
			</div>
		</div>

		<!--Google Map-->

		<div class="row">
			<div class="col-md-12">
				<div class="map"></div> MAP
				<style>
					#map{
						width: 500px;
						height: 400px;
					}
				</style>

    		<div id="map"></div>

    		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAa7in_wDphh1PEei-A6Oqi1P5R261X5GE&callback=initMap"
		    async defer></script>

		    <script>
		      function initMap() {
		        // Create a map object and specify the DOM element for display.
		        var map = new google.maps.Map(document.getElementById('map'), {
		          center: {lat: <%= @place.latitude %>, lng: <%= @place.longitude%>},
		          scrollwheel: false,
		          zoom: 14
		        });  

		        var marker = new google.maps.Marker({
		        	position: new google.maps.LatLng(<%= @place.latitude %>, <%= @place.longitude %>),
		        	title: "我家!" 
		        }); 

		        marker.setMap(map);    
		      }

		    </script>

			</div>
		</div>
	</div>
</div>

app/views/places/update.html.erb
<h1>Places#update</h1>
<p>Find me in app/views/places/update.html.erb</p>